# -*- coding: utf-8 -*-
"""Medical ChatBot Text2text,Voice & Voice to Voice_xuan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWlsvUAwfvRv8w2RM2Oh45LBYN--Wgeg
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
balajikartheek_medical_assistance_dataset_path = kagglehub.dataset_download('balajikartheek/medical-assistance-dataset')

print('Data source import complete.')

"""## **Import and load the data file**

## Test the functionality with the App here: [MedBot](https://www.kaggle.com/discussions/general/497039)

We import the necessary packages for our chatbot and initialize the variables we will use in our Python project.
The data file is in JSON format so we used the json package to parse the JSON file into Python.
"""

import nltk
nltk.download('punkt')      #Sentence tokenizer

import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
import json
import pickle
import warnings
warnings.filterwarnings('ignore')

!pip install tensorflow

import tensorflow as tf
print(tf.__version__)

import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import SGD
import random

import keras
print(keras.__version__)

"""# **Preprocessing**"""

words=[]
classes = []
documents = []
ignore_words = ['?', '!']

# data_file = open('/kaggle/input/medical-assistance-dataset/intents.json').read() # read json file
# intents = json.loads(data_file) # load json file

import json
# Build full path to the file
file_path = balajikartheek_medical_assistance_dataset_path + '/intents.json'
# Read JSON file
with open(file_path, 'r') as f:
    intents = json.load(f)

"""When working with text data, we need to perform various preprocessing on the data before we make a machine learning or a deep learning model. Based on the requirements we need to apply various operations to preprocess the
data.
- Tokenizing is the most basic and first thing you can do on text data.
- Tokenizing is the process of breaking the whole text into small parts like words.
- Here we iterate through the patterns and tokenize the sentence using nltk.word_tokenize() function and append each word in the words list. We also create a list of classes for our tags.
"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

for intent in intents['intents']:
    for pattern in intent['patterns']:
        #tokenize each word
        w = nltk.word_tokenize(pattern)
        words.extend(w)# add each elements into list
        #combination between patterns and intents
        documents.append((w, intent['tag']))#add single element into end of list
        # add to tag in our classes list
        if intent['tag'] not in classes:
            classes.append(intent['tag'])

nltk.download('wordnet') #lexical database for the English language

nltk.download('omw-1.4')

"""Now we will lemmatize each word and remove duplicate words from the list.
- Lemmatizing is the process of converting a word into its lemma form and then creating a pickle file to store the Python objects which we will use while predicting.
"""

# lemmatize, lower each word and remove duplicates
words = [lemmatizer.lemmatize(w.lower()) for w in words if w not in ignore_words]
words = sorted(list(set(words)))
# sort classes
classes = sorted(list(set(classes)))
# documents = combination between patterns and intents
print (len(documents), "documents\n", documents, "\n")
# classes = intents[tag]
print (len(classes), "classes\n", classes, "\n")
# words = all words, vocabulary
print (len(words), "unique lemmatized words\n", words, "\n")
pickle.dump(words,open('words.pkl','wb'))
pickle.dump(classes,open('classes.pkl','wb'))

"""# **Training Model**

Now, we will create the training data in which we will provide the input and the output.
- Our input will be the pattern and output will be the class our input pattern belongs to. But the computer doesn’t understand text so we will convert text into numbers
"""

!pip install numpy

import numpy as np
import random

# Create empty lists for bags and output_rows
bags = []
output_rows = []

# Iterate through documents to create bags and output_rows
for doc in documents:
    bag = []
    pattern_words = doc[0]
    pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]

    # Create a bag for the current document
    for w in words:
        bag.append(1) if w in pattern_words else bag.append(0)

    # Create the output row for the current document
    output_row = [0] * len(classes)
    output_row[classes.index(doc[1])] = 1

    # Append the bag and output_row to their respective lists
    bags.append(bag)
    output_rows.append(output_row)

# Convert bags and output_rows to numpy arrays
bags = np.array(bags)
output_rows = np.array(output_rows)

# Combine bags and output_rows into a list of tuples
training = list(zip(bags, output_rows))

# Shuffle training
random.shuffle(training)

# Convert bags and output_rows back to lists for easier indexing
bags, output_rows = zip(*training)

# Convert bags and output_rows to numpy arrays
bags = np.array(bags)
output_rows = np.array(output_rows)

# Split into train and test sets
train_x = bags
train_y = output_rows

# Use the same data for the test for now (you might want to split differently)
test_x = train_x
test_y = train_y

print("Training data created")

from tensorflow.python.framework import ops
ops.reset_default_graph()

"""# **Build the model**

We have our training data ready, now we will build a deep neural network that has 3 layers. We use the Keras sequential API for this. After training the model for 200 epochs, we achieved 100% accuracy on our model. Let us save the model as ‘chatbot_model.h5'.
"""

# Create the model
model = Sequential()
model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(train_y[0]), activation='softmax'))

# Compile the model using Adam optimizer without weight_decay
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# # Create model - 3 layers. First layer 128 neurons, second layer 64 neurons and 3rd output layer contains number of neurons
# # equal to number of intents to predict output intent with softmax
# model = Sequential()
# model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(len(train_y[0]), activation='softmax'))
# print("First layer:",model.layers[0].get_weights()[0])

# model = Sequential()
# model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(len(train_y[0]), activation='softmax'))
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
hist = model.fit(np.array(train_x), np.array(train_y), epochs=75, batch_size=5, verbose=1)

model.save('medical_chatbot_model.h5')

# # Compile model. Stochastic gradient descent with Nesterov accelerated gradient gives good results for this model
# # sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# #fitting and saving the model
# hist = model.fit(np.array(train_x), np.array(train_y), epochs=75, batch_size=5, verbose=1)
# model.save('medical_chatbot_model.h5')

# print("model created")

from keras.models import load_model
model1 = load_model('medical_chatbot_model.h5')

from sklearn.model_selection import train_test_split

train_x, val_x, train_y, val_y = train_test_split(train_x, train_y, test_size=0.1, random_state=42)

# Evaluate the model on the test set
loss, accuracy = model1.evaluate(np.array(test_x), np.array(test_y), verbose=1)
print("Test loss:", loss)
print("Test accuracy:", accuracy)

import tensorflow as tf
import keras
import numpy as np
import nltk

print("TensorFlow version:", tf.__version__)
print("Keras version:", keras.__version__)
print("NumPy version:", np.__version__)
print("NLTK version:", nltk.__version__)

"""# FOR PREDICTING RESPONSE

"""

from google.colab import drive
drive.mount('/content/drive')

#intents = json.loads(open('/content/drive/MyDrive/Asan Innovators/MedicalChatBot/intents.json').read())
intents = json.loads(open('/content/drive/MyDrive/Colab Notebooks/Medical ChatBot/intents.json').read())

words = pickle.load(open('words.pkl','rb'))

classes = pickle.load(open('classes.pkl','rb'))

def clean_up_sentence(sentence):

# tokenize the pattern - split words into array

  sentence_words = nltk.word_tokenize(sentence)
#print(sentence_words)
# stem each word - create short form for word

  sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]
#print(sentence_words)b

  return sentence_words

def bow(sentence, words, show_details=True):

# tokenize the pattern

  sentence_words = clean_up_sentence(sentence)
  #print(sentence_words)

  # bag of words - matrix of N words, vocabulary matrix

  bag = [0]*len(words)
  #print(bag)

  for s in sentence_words:
      for i,w in enumerate(words):
          if w == s:
              # assign 1 if current word is in the vocabulary position
              bag[i] = 1
              if show_details:
                  print ("found in bag: %s" % w)
              #print ("found in bag: %s" % w)
  #print(bag)
  return(np.array(bag))

def predict_class(sentence, model):

  # filter out predictions below a threshold

  p = bow(sentence, words,show_details=False)
  #print(p)

  res = model.predict(np.array([p]))[0]
  #print(res)

  ERROR_THRESHOLD = 0.25

  results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
  #print(results)
  # sort by strength of probability

  results.sort(key=lambda x: x[1], reverse=True)
  #print(results)

  return_list = []

  for r in results:
      return_list.append({"intent": classes[r[0]], "probability": str(r[1])})

  return return_list
  #print(return_list)

def getResponse(ints, intents_json):

  tag = ints[0]['intent']
  #print(tag)

  list_of_intents = intents_json['intents']
  #print(list_of_intents)

  for i in list_of_intents:
      if(i['tag']== tag):
          result = random.choice(i['responses'])
          break
  return result

def chatbot_response(text):
  ints = predict_class(text, model)

  #print(ints)

  res = getResponse(ints, intents)
  #print(res)
  return res

"""# Predicting results"""

start = True
while start:

  query = input('Enter Message:')
  if query in ['quit','exit','bye']:
      start = False
      continue
  try:
      res = chatbot_response(query)
      print(res)
  except:
      print('You may need to rephrase your question.')

"""# Text to Text"""

start = True
while start:

  query = input('Enter Message:')
  if query in ['quit','exit','bye']:
      start = False
      continue
  try:
      res = chatbot_response(query)
      print(res)
  except:
      print('You may need to rephrase your question.')

!pip install gtts

"""# Text to Voice & Text"""

import nltk
nltk.download('punkt')  # Sentence tokenizer
import nltk
from nltk.stem import WordNetLemmatizer
import json
import pickle
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import SGD
import random
from gtts import gTTS
from IPython.display import Audio, display

# Your existing code...

start = True
while start:
    query = input('Enter Message:')
    if query.lower() in ['quit', 'exit', 'bye']:
        start = False
        continue

    try:
        res = chatbot_response(query)
        print(res)

        # Convert the response to speech
        tts = gTTS(text=res, lang='en')
        tts.save("response.mp3")

        # Play the response
        display(Audio(filename="response.mp3", autoplay=True))

    except Exception as e:
        print(f'Error: {e}')

!pip install gtts

!pip install SpeechRecognition

!apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

!pip install pyaudio

import speech_recognition as sr

# Print the list of available audio input devices and their indices
print(sr.Microphone.list_microphone_names())

!pip install SpeechRecognition pydub

import nltk
nltk.download('punkt')  # Sentence tokenizer
from nltk.stem import WordNetLemmatizer
import json
import pickle
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import SGD
import random
from gtts import gTTS
from IPython.display import Audio, display
from pydub import AudioSegment
from pydub.playback import play
import speech_recognition as sr

# Patch the speech_recognition library to use pydub for audio playback
def patched_play_mp3(audio_file, start=0, end=None):
    audio = AudioSegment.from_mp3(audio_file)
    play(audio[start:end])

sr.AudioFile.play_mp3 = patched_play_mp3

# Your existing code...

def get_voice_input():
    recognizer = sr.Recognizer()
    microphone = sr.Microphone()

    with microphone as source:
        print("Say something:")
        recognizer.adjust_for_ambient_noise(source)
        audio = recognizer.listen(source, timeout=5)

    try:
        text = recognizer.recognize_google(audio)
        print("You said:", text)

        # Convert the recognized text to an audio file
        tts = gTTS(text=text, lang='en')
        tts.save("input_audio.mp3")

        # Play the captured audio
        play(AudioSegment.from_mp3("input_audio.mp3"))

        return "input_audio.mp3"

    except sr.UnknownValueError:
        print("Could not understand audio.")
        return None
    except sr.RequestError as e:
        print(f"Error connecting to Google API: {e}")
        return None

# The rest of your code...

!pip install pydub sounddevice

!pip install pyttsx3

!pip install ffmpeg-python

!pip install SpeechRecognition pydub

from IPython.display import HTML, Audio
from google.colab.output import eval_js
from base64 import b64decode
from pydub import AudioSegment
from pydub.playback import play
import time
import io
from pydub import AudioSegment
from pydub.playback import play
import ffmpeg
import numpy as np
from scipy.io.wavfile import read as wav_read

AUDIO_HTML = """
<script>
var my_div = document.createElement("DIV");
var my_p = document.createElement("P");
var my_btn = document.createElement("BUTTON");
var t = document.createTextNode("Press to start recording");

my_btn.appendChild(t);
my_div.appendChild(my_btn);
document.body.appendChild(my_div);

var base64data = 0;
var reader;
var recorder, gumStream;
var recordButton = my_btn;

var handleSuccess = function(stream) {
  gumStream = stream;
  var options = {
    mimeType : 'audio/webm;codecs=opus'
  };
  recorder = new MediaRecorder(stream);
  recorder.ondataavailable = function(e) {
    var url = URL.createObjectURL(e.data);
    var preview = document.createElement('audio');
    preview.controls = true;
    preview.src = url;
    document.body.appendChild(preview);

    reader = new FileReader();
    reader.readAsDataURL(e.data);
    reader.onloadend = function() {
      base64data = reader.result;
    }
  };
  recorder.start();
};

recordButton.innerText = "Recording... press to stop";

navigator.mediaDevices.getUserMedia({audio: true}).then(handleSuccess);

function toggleRecording() {
  if (recorder && recorder.state == "recording") {
      recorder.stop();
      gumStream.getAudioTracks()[0].stop();
      recordButton.innerText = "Saving the recording... pls wait!"
  }
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

var data = new Promise(resolve=>{
recordButton.onclick = ()=>{
toggleRecording()

sleep(2000).then(() => {
  resolve(base64data.toString())
});
}
});

</script>
"""

"""# Voice to Voice"""

def get_audio():
    display(HTML(AUDIO_HTML))
    data = eval_js("data")

    if not data:
        return None, None

    binary = b64decode(data.split(',')[1])

    # Convert audio data to pydub AudioSegment
    audio_segment = AudioSegment.from_file(io.BytesIO(binary), format="webm")

    # Convert to mono channel
    audio_segment = audio_segment.set_channels(1)

    # Convert to 16-bit PCM format
    audio_segment = audio_segment.set_sample_width(2)

    # Convert to 16 kHz sample rate
    audio_segment = audio_segment.set_frame_rate(16000)

    # Save the processed audio to a file
    audio_segment.export("audio.wav", format="wav")

    # Read the processed audio file
    sr, audio = wav_read("audio.wav")

    return audio, sr

start = True
while start:
    query_audio, _ = get_audio()

    if query_audio is not None:
        try:
            res = chatbot_response(query_audio)
            print(res)

            # Convert the response to speech
            tts = gTTS(text=res, lang='en')
            tts.save("response.mp3")

            # Play the response
            display(Audio(filename="response.mp3", autoplay=True))

        except Exception as e:
            print(f'Error: {e}')

    # Add a delay after processing to prevent continuous recording
    time.sleep(5)  # You can adjust the delay as needed
    start = False  # Stop the recording loop after the first iteration

import speech_recognition as sr
from gtts import gTTS
from IPython.display import Audio, display

def speech_to_text(audio_file):
    recognizer = sr.Recognizer()

    with sr.AudioFile(audio_file) as source:
        audio = recognizer.record(source)

    try:
        text = recognizer.recognize_google(audio)
        return text
    except sr.UnknownValueError:
        print("Could not understand audio.")
        return None
    except sr.RequestError as e:
        print(f"Error connecting to Google API: {e}")
        return None

# Get the text from "audio.wav"
audio_text = speech_to_text("audio.wav")

# Ask the bot using the detected text
if audio_text:
    try:
        res = chatbot_response(audio_text)
        print(res)

        # Convert the response to speech
        tts = gTTS(text=res, lang='en')
        tts.save("response.mp3")

        # Play the response
        display(Audio(filename="response.mp3", autoplay=True))

    except Exception as e:
        print(f'Error: {e}')

